### ISSUE TITLE
It doesn't rendering the HTML files in directory

### ISSUE THREAD

**Issue by srinivashappy** [kamlekar/HTML-Skinning-Boilerplate#1]
- I Followed the steps to install gulp and gulp-nun-jucks-render etc.., 
- Now run the command line as you instructed.
- I didn't found the html file in the site directory.

**Comment by kamlekar** [comment]
Thanks @srinivashappy I will look into this and will let you know soon.

**Comment by kamlekar** [comment]
You should keep the files in the drive on which nodejs is installed. AFAIK, you might have kept the files in other drive. Please check it and reply me soon.
