### ISSUE TITLE
Rename project folders

### ISSUE THREAD

**Issue by rustemgareev** [kamlekar/HTML-Skinning-Boilerplate#20]
Ok, now we have this folders structure in templates-pre:
| templates-pre
|---sections
|---variables
|---index.html

So imagine we need to create folders in our site, for adding a shop for example so structure will be:
| templates-pre
|---sections
|---shop
|    |---shop-index.html
|---variables
|---index.html

So it's better to rename templating folders with underscore prefix to distinct where is site and where are templating:
| templates-pre
|---_sections
|---_variables
|---shop
|    |---shop-index.html
|---index.html

Ok? If ok, next problem will appear...

**Comment by kamlekar** [comment]
Currently, the naming conventions for the folders are quite poor. I will consider your suggestion once I rename those folders to some good names. Thanks.

**Comment by rustemgareev** [comment]
Yes, maybe change structure of project to this?:
-dist folder
-src folder
gulpfile.js
README.md.

Dist folder will be instead of current "site".
In src we will have the rest needed for templating, so it will look this way:
src:
|---_html-components (instead of "variables")
|---_html-layout (instead of "sections")
|---_scss folder (instead of "sass")
|---assets folder (so we could generate scss here and add source files
|---index.html
...
So we could use src-folder for prototype our site, and dist folder just for pure output - ready site?

**Comment by rustemgareev** [comment]
Ups, I haven't considered that adding assets and images both in src and dist will double project size. So my second variant for structure is:
project
|--html (instead of templates)
|--scss (sass)
|--svg (bundle svgs)
|--www (instead of site)
|--|--assets
|--|--data
gulpfile.js
README.md

Advantage of this is that alphabetical order corresponds with ierarchy of importance - first we need edit html templates, then sass, then svgs, and getting output in www folder.

**Comment by kamlekar** [comment]
It seems you are a .net dev. The directory looks familiar to .net's directory :). I am actually planning to refer the directory structure of jekyll. https://github.com/jekyll/jekyll

**Comment by rustemgareev** [comment]
It's just a self-explaining structure, but choice is for you of course...

**Comment by kamlekar** [comment]
No, I am not trying to be biased here. The thing is if I go with .net structure, non .net devs can't understand the structure. The Jekyll is a globally known structure so I am referring it. I hope you can understand. But if you have any other globally known directory structures, do please share it.

**Comment by kamlekar** [comment]
Please check this [branch](https://github.com/kamlekar/HTML-Skinning-Boilerplate/tree/change-dir) where I added these changes.

**Comment by rustemgareev** [comment]
I didn't mean underscore prefix for overall folders, just for templates (_sections / _variables) - which contain files that won't be compiled. I looked at Jekyll - they have such logic in "site" folder.

**Comment by kamlekar** [comment]
Yup you are right. will do changes accordingly and update the branch.

**Comment by kamlekar** [comment]
Check the updated Change-dir branch. Somehow the branch repo is failing. I suspect even the master branch is failing. need to check it.

**Comment by rustemgareev** [comment]
Normal now.
