### ISSUE TITLE
Need to add new variable for relative paths

### ISSUE THREAD

**Issue by rustemgareev** [kamlekar/HTML-Skinning-Boilerplate#29]
Hi, I think it will be useful to add new variable "path" to existing "css_path", "js_path", "img_path".
So we can easily set relativeness of our folders. Explanation: I have such project strucure:
<pre>project/
|  sass/
|  site/
|  templates-pre/
|  |  shop/
|  |  |  shop.html
|  index.html</pre>
<p>In compiled <code>site/shop/shop.html</code> I have the same css/img/js paths as in <code>site/index.html</code> because <code>css_path</code> is unchangeable and set one time).</p>
<p>But if I have new <code>path</code> variable I set skeleton css/js/img paths that way:</P>
<pre>
<code>
&#60;link href="{{path}}{{css_path}}main.css" /&#62;
&#60;script src="{{path}}{{css_path}}scripts.js" /&#62;
</code>
</pre>
And in <code>templates-pre/shop/shop.html</code> I set <code>path</code> variable to relative path:
<pre>
{% set path="../" %}
</pre>
So in site/shop/shop.html I have my relative paths:
<pre>
<code>
&#60;link href="../assets/css/main.css" /&#62;
&#60;script src="../assets/js/scripts.js" /&#62;
</code>
</pre>
That works fine for me.
Sorry I have no time to go deeper for github but I can only sketch my suggestions that way.

**Comment by kamlekar** [comment]
> Sorry I have no time to go deeper for github but I can only sketch my suggestions that way.

@rustemgareev yeah no problem. 

Lets keep the values hardcoded as they are now. It is clear that if user wants (as you are), he/she will modify as necessary.

**Comment by rustemgareev** [comment]
Well, what I'm suggesting is a hard coding, but it's a core need, because without that it won't work at all.

**Comment by kamlekar** [comment]
hmm.. but currently there are no html files which are compiling in a folder. I am keeping all the compiling files as immediate children to `templates-pre` folder. Even if I consider to add `{% set path="../" %}`, I can't add anywhere in the current structure of boilerplate because all the indirectly compiling files present in folders (prefixed as `_`).

**Comment by rustemgareev** [comment]
Sorry I can't get last sentence.

**Comment by rustemgareev** [comment]
By the way that's improved code for what I want get:
<pre>
<code>
/* skeleton-content.html */
{% set css_path = path+css_path %}
{% set js_path = path+js_path %}
{% set img_path = path+img_path %}
&#60;html&#62;
...
&#60;link href="{{ css_path }}" /&#62;
...
&#60;img src="{{ img_path }}" /&#62;
...
&#60;script src="{{ js_path }}" /&#62;
...
</code>
</pre>

/* gulpfile.js */
...
css_path: assetsPath.css;
js_path: assetsPath.js;
img_path: assetsPath.img;
path: '';
...

/* And if we have templates-pre/inner-folder/inner-index.html */
{% set path="../" %}

**Comment by kamlekar** [comment]
What I am trying to say is there is no `templates-pre/inner-folder/inner-index.html` structure in this Boilerplate currently. In inner-folders I have only `components` and `variables`. After compiling, the files will be compiled to `site/index.html` or `site/index2.html` but not `site/some_folder/inner-index.html`.

**Comment by rustemgareev** [comment]
But predict that user may have complex structure, and instead of opening issue and asking you how to set relative paths for assets ("../" or "../../") you will already have solution! :)

**Comment by kamlekar** [comment]
No the thing is I am unable to understand in which file exactly I should keep this variable?

**Comment by rustemgareev** [comment]
Look at my previous comment starting with _By the way that's improved code for what I want get:_
They are defined first in gulpfile.js, then in skeleton-content.html and then in every .html file in nested folders. (site/inner-folder/index.html for example)

**Comment by kamlekar** [comment]
It is better that you suggest the changes with a pull request (to "pr-branch"). Clearly, I am unable to visualize exactly of how this will be useful. Please send a PR when you have time :)

**Comment by kamlekar** [comment]
@rustemgareev Hi, I hope you are not mad at me as you stopped contributing. The changes you are suggesting will assume the complexity of the directory structure. Let's leave that to the devs who will use this Boilerplate. As per there need, they will add variables as you are suggesting. If we add from now only, it will lead to confusing, IMO. Thanks for your contributions.

**Comment by rustemgareev** [comment]
Hi, I can't contribute just only because of no time, so if I only had it more, I would help.
Yes, I agree that some suggestions are too complex, so if I will have ideas for simplifying, I'll try to bring them to you
